<a href="https://colab.research.google.com/github/Mukish45/Plant-Disease-Identification/blob/main/Potato_Disease_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPool2D, Flatten, Dense, Dropout

import os
import shutil
import zipfile

In [3]:
local_zip = 'C:/Users/Theeraj/Downloads/archive (1).zip'
zip_ref = zipfile.ZipFile(local_zip, 'r')
print(zip_ref)
zip_ref.extractall()

<zipfile.ZipFile filename='C:/Users/Theeraj/Downloads/archive (1).zip' mode='r'>


In [5]:
print(len(os.listdir(r'C:\Users\Theeraj\Downloads\Potato-Disease-Identification-main\Potato\Test\Potato___Early_blight')))
print(len(os.listdir(r'C:\Users\Theeraj\Downloads\Potato-Disease-Identification-main\Potato\Test\Potato___healthy')))
print(len(os.listdir(r'C:\Users\Theeraj\Downloads\Potato-Disease-Identification-main\Potato\Test\Potato___Late_blight')))

100
100
100


In [ ]:
print(len(os.listdir('/content/PLD_3_Classes_256/Training/Early_Blight')))
print(len(os.listdir('/content/PLD_3_Classes_256/Training/Healthy')))
print(len(os.listdir('/content/PLD_3_Classes_256/Training/Late_Blight')))

1303
816
1132


In [ ]:
print(len(os.listdir('/content/PLD_3_Classes_256/Validation/Early_Blight')))
print(len(os.listdir('/content/PLD_3_Classes_256/Validation/Healthy')))
print(len(os.listdir('/content/PLD_3_Classes_256/Validation/Late_Blight')))

163
102
151


In [ ]:
os.mkdir('train')
os.mkdir('valid')
os.mkdir('test')

In [ ]:
os.mkdir('train/Early_Blight')
os.mkdir('train/Healthy')
os.mkdir('train/Late_Blight')

os.mkdir('valid/Early_Blight')
os.mkdir('valid/Healthy')
os.mkdir('valid/Late_Blight')

os.mkdir('test/Early_Blight')
os.mkdir('test/Healthy')
os.mkdir('test/Late_Blight')

In [ ]:
print(len(os.listdir(('/content/PLD_3_Classes_256/Training/Early_Blight'))))

1303


In [ ]:
dir_1 = '/content/PLD_3_Classes_256/Training/Early_Blight'
dir_2 = '/content/train/Early_Blight'

dir1_lst = os.listdir(dir_1)
dir1_lst.sort()

for img in dir1_lst[:815]:
  shutil.move(os.path.join(dir_1, img), os.path.join(dir_2, img))



dir_1 = '/content/PLD_3_Classes_256/Testing/Early_Blight'
dir_2 = '/content/test/Early_Blight'

dir1_lst = os.listdir(dir_1)
dir1_lst.sort()

for img in dir1_lst[:]:
  shutil.move(os.path.join(dir_1, img), os.path.join(dir_2, img))



dir_1 = '/content/PLD_3_Classes_256/Validation/Early_Blight'
dir_2 = '/content/valid/Early_Blight'

dir1_lst = os.listdir(dir_1)
dir1_lst.sort()

for img in dir1_lst[:100]:
  shutil.move(os.path.join(dir_1, img), os.path.join(dir_2, img))

In [ ]:
print(len(os.listdir(('/content/train/Early_Blight'))))
print(len(os.listdir(('/content/test/Early_Blight'))))
print(len(os.listdir(('/content/valid/Early_Blight'))))

815
162
100


In [ ]:
dir_1 = '/content/PLD_3_Classes_256/Training/Healthy'
dir_2 = '/content/train/Healthy'

dir1_lst = os.listdir(dir_1)
dir1_lst.sort()

for img in dir1_lst[:815]:
  shutil.move(os.path.join(dir_1, img), os.path.join(dir_2, img))



dir_1 = '/content/PLD_3_Classes_256/Testing/Healthy'
dir_2 = '/content/test/Healthy'

dir1_lst = os.listdir(dir_1)
dir1_lst.sort()

for img in dir1_lst[:]:
  shutil.move(os.path.join(dir_1, img), os.path.join(dir_2, img))



dir_1 = '/content/PLD_3_Classes_256/Validation/Healthy'
dir_2 = '/content/valid/Healthy'

dir1_lst = os.listdir(dir_1)
dir1_lst.sort()

for img in dir1_lst[:100]:
  shutil.move(os.path.join(dir_1, img), os.path.join(dir_2, img))

In [ ]:
print(len(os.listdir(('/content/train/Healthy'))))
print(len(os.listdir(('/content/test/Healthy'))))
print(len(os.listdir(('/content/valid/Healthy'))))

815
102
100


In [ ]:
dir_1 = '/content/PLD_3_Classes_256/Training/Late_Blight'
dir_2 = '/content/train/Late_Blight'

dir1_lst = os.listdir(dir_1)
dir1_lst.sort()

for img in dir1_lst[:815]:
  shutil.move(os.path.join(dir_1, img), os.path.join(dir_2, img))



dir_1 = '/content/PLD_3_Classes_256/Testing/Late_Blight'
dir_2 = '/content/test/Late_Blight'

dir1_lst = os.listdir(dir_1)
dir1_lst.sort()

for img in dir1_lst[:]:
  shutil.move(os.path.join(dir_1, img), os.path.join(dir_2, img))



dir_1 = '/content/PLD_3_Classes_256/Validation/Late_Blight'
dir_2 = '/content/valid/Late_Blight'

dir1_lst = os.listdir(dir_1)
dir1_lst.sort()

for img in dir1_lst[:100]:
  shutil.move(os.path.join(dir_1, img), os.path.join(dir_2, img))

In [ ]:
print(len(os.listdir(('/content/train/Late_Blight'))))
print(len(os.listdir(('/content/test/Late_Blight'))))
print(len(os.listdir(('/content/valid/Late_Blight'))))

815
141
100


In [ ]:
train_data_gen = ImageDataGenerator(rescale=1/255)
validation_data_gen = ImageDataGenerator(rescale=1/255)
test_data_gen = ImageDataGenerator(rescale=1/255)


train_gen = train_data_gen.flow_from_directory(
    '/content/train',
    target_size = (256,256),
    batch_size = 32,
    class_mode = 'categorical'
)

val_gen = train_data_gen.flow_from_directory(
    '/content/valid',
    target_size = (256,256),
    batch_size = 16,
    class_mode = 'categorical'
)

test_gen = train_data_gen.flow_from_directory(
    '/content/test',
    target_size = (256,256),
    batch_size = 8,
    class_mode = 'categorical'
)

Found 2445 images belonging to 3 classes.
Found 300 images belonging to 3 classes.
Found 405 images belonging to 3 classes.


In [ ]:
model = Sequential()
model.add(layers.Conv2D(input_shape=(256, 256, 3), filters=64,kernel_size=(3,3), padding="same",activation='relu'))
model.add(layers.Conv2D(filters=32,kernel_size=(3,3), padding="same",activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))

In [ ]:
model.add(layers.Flatten())
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(3,activation='softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 256, 256, 64)      1792      
                                                                 
 conv2d_1 (Conv2D)           (None, 256, 256, 32)      18464     
                                                                 
 max_pooling2d (MaxPooling2D  (None, 128, 128, 32)     0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 126, 126, 128)     36992     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 63, 63, 128)      0         
 2D)                                                             
                                                                 
 conv2d_3 (Conv2D)           (None, 61, 61, 64)        7

In [ ]:
from tensorflow.keras.optimizers import Adam
model.compile(loss = 'categorical_crossentropy',
             optimizer = 'Adam',
             metrics = ['accuracy'])

In [ ]:
model_fit = model.fit(train_gen,
                     epochs = 10,
                    verbose = 1,
                     validation_data = val_gen)

Epoch 1/10
77/77 [==============================] - 27s 210ms/step - loss: 1.0543 - accuracy: 0.4270 - val_loss: 1.0669 - val_accuracy: 0.3933
Epoch 2/10
77/77 [==============================] - 14s 182ms/step - loss: 0.9219 - accuracy: 0.6078 - val_loss: 0.8910 - val_accuracy: 0.6400
Epoch 3/10
77/77 [==============================] - 14s 183ms/step - loss: 0.8660 - accuracy: 0.6249 - val_loss: 0.8217 - val_accuracy: 0.6667
Epoch 4/10
77/77 [==============================] - 14s 184ms/step - loss: 0.7672 - accuracy: 0.6822 - val_loss: 0.7162 - val_accuracy: 0.6933
Epoch 5/10
77/77 [==============================] - 14s 187ms/step - loss: 0.7090 - accuracy: 0.6973 - val_loss: 0.6826 - val_accuracy: 0.7467
Epoch 6/10
77/77 [==============================] - 14s 185ms/step - loss: 0.6454 - accuracy: 0.7354 - val_loss: 0.6893 - val_accuracy: 0.6933
Epoch 7/10
77/77 [==============================] - 14s 186ms/step - loss: 0.6475 - accuracy: 0.7280 - val_loss: 0.6698 - val_accuracy: 0.7233

In [ ]:
score = model.evaluate(test_gen, verbose=0)

In [ ]:
print("Accuracy of evaluation data is ",score[1])

Accuracy of evaluation data is  0.8913580179214478


In [ ]:
model.save('new_simple_model.h5')

In [ ]:
preds = model.predict(test_gen)

51/51 [==============================] - 1s 21ms/step


In [ ]:
import numpy as np
prediction = np.argmax(preds, axis = 1)

In [ ]:
prediction

array([0, 0, 1, 0, 1, 0, 2, 0, 0, 1, 1, 1, 2, 2, 1, 0, 2, 2, 2, 0, 1, 2,
       2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 2, 0, 0, 1, 0, 0, 0, 0, 0, 2,
       1, 1, 0, 2, 2, 2, 1, 2, 0, 2, 0, 1, 0, 2, 0, 1, 2, 0, 0, 0, 0, 2,
       1, 1, 0, 2, 0, 2, 0, 1, 1, 0, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 0, 2,
       2, 0, 1, 1, 0, 2, 0, 2, 2, 0, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2, 1, 1,
       1, 0, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 2, 0, 1, 2, 1, 0, 2, 1, 0, 0,
       0, 0, 2, 2, 2, 2, 0, 2, 1, 0, 0, 0, 2, 2, 2, 0, 2, 2, 1, 1, 0, 0,
       0, 0, 2, 0, 2, 1, 0, 2, 2, 0, 1, 1, 1, 0, 0, 0, 2, 2, 2, 2, 1, 0,
       0, 1, 0, 2, 0, 0, 0, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 1, 2, 2, 2, 0,
       0, 2, 2, 1, 2, 2, 1, 0, 0, 0, 0, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 2,
       1, 0, 0, 0, 0, 2, 1, 0, 1, 1, 0, 2, 0, 0, 0, 2, 2, 1, 0, 0, 2, 1,
       0, 0, 1, 2, 0, 0, 2, 2, 2, 0, 1, 2, 0, 2, 0, 1, 1, 0, 1, 0, 0, 2,
       0, 1, 1, 0, 2, 1, 2, 2, 1, 0, 0, 2, 1, 2, 2, 1, 0, 0, 1, 2, 2, 2,
       2, 0, 2, 2, 2, 1, 2, 2, 0, 2, 2, 0, 2, 0, 1,

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
print(confusion_matrix(test_gen.labels, prediction))

[[65 36 61]
 [45 23 34]
 [50 38 53]]


In [ ]:
preds = model.predict(train_gen)
prediction = np.argmax(preds, axis = 1)
print(confusion_matrix(train_gen.labels, prediction))

77/77 [==============================] - 6s 81ms/step
[[276 278 261]
 [262 282 271]
 [293 245 277]]


In [ ]:
model3 = tf.keras.Sequential([
    layers.Conv2D(32,(3,3),activation='relu',input_shape=(256,256,3)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(64,activation='relu'),
    layers.Dense(3,activation='softmax'),
])

In [ ]:
model3.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_7 (Conv2D)           (None, 254, 254, 32)      896       
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 127, 127, 32)     0         
 2D)                                                             
                                                                 
 conv2d_8 (Conv2D)           (None, 125, 125, 64)      18496     
                                                                 
 max_pooling2d_7 (MaxPooling  (None, 62, 62, 64)       0         
 2D)                                                             
                                                                 
 conv2d_9 (Conv2D)           (None, 60, 60, 64)        36928     
                                                                 
 max_pooling2d_8 (MaxPooling  (None, 30, 30, 64)      

In [ ]:
model3.compile(loss = 'categorical_crossentropy',
             optimizer = 'Adam',
             metrics = ['accuracy'])

In [ ]:
model3_fit = model3.fit(train_gen,
                      epochs = 20,
                      verbose = 1,
                      validation_data = val_gen)

Epoch 1/20
77/77 [==============================] - 9s 102ms/step - loss: 1.0222 - accuracy: 0.4695 - val_loss: 0.8724 - val_accuracy: 0.6167
Epoch 2/20
77/77 [==============================] - 7s 91ms/step - loss: 0.9301 - accuracy: 0.5873 - val_loss: 0.8533 - val_accuracy: 0.5767
Epoch 3/20
77/77 [==============================] - 7s 90ms/step - loss: 0.8404 - accuracy: 0.6605 - val_loss: 0.6592 - val_accuracy: 0.7967
Epoch 4/20
77/77 [==============================] - 7s 89ms/step - loss: 0.6820 - accuracy: 0.7202 - val_loss: 0.5406 - val_accuracy: 0.7833
Epoch 5/20
77/77 [==============================] - 7s 89ms/step - loss: 0.5353 - accuracy: 0.7845 - val_loss: 0.4581 - val_accuracy: 0.8300
Epoch 6/20
77/77 [==============================] - 7s 88ms/step - loss: 0.4495 - accuracy: 0.8278 - val_loss: 0.3837 - val_accuracy: 0.8333
Epoch 7/20
77/77 [==============================] - 7s 88ms/step - loss: 0.3400 - accuracy: 0.8736 - val_loss: 0.2886 - val_accuracy: 0.8933
Epoch 8/20
7

In [ ]:
score = model3.evaluate(test_gen, verbose=0)

In [ ]:
print("Accuracy of evaluation data is ",score[1])

Accuracy of evaluation data is  0.9580246806144714


In [ ]:
preds = model3.predict(train_gen)
prediction = np.argmax(preds, axis = 1)
print(confusion_matrix(train_gen.labels, prediction))

77/77 [==============================] - 5s 69ms/step
[[273 269 273]
 [276 261 278]
 [258 292 265]]


In [ ]:
model3.save('medium_model.h5')

In [ ]:
model4 = tf.keras.Sequential([
    layers.Conv2D(256,(3,3),activation='LeakyReLU',input_shape=(256,256,3)),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(128,(3,3),activation='LeakyReLU'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(64,(3,3),activation='LeakyReLU'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(32,(3,3),activation='LeakyReLU'),
    layers.MaxPooling2D((2,2)),
    layers.Conv2D(16,(3,3),activation='LeakyReLU'),
    layers.MaxPooling2D((2,2)),
    layers.Flatten(),
    layers.Dense(128,activation='LeakyReLU'),
    layers.Dense(64,activation='LeakyReLU'),
    layers.Dense(3,activation='softmax'),
])

In [ ]:
model4.compile(loss = 'categorical_crossentropy',
             optimizer = 'Adam',
             metrics = ['accuracy'])

In [ ]:
model4_fit = model4.fit(train_gen,
                      epochs = 20,
                      verbose = 1,
                      validation_data = val_gen)

Epoch 1/20
77/77 [==============================] - 30s 377ms/step - loss: 1.0408 - accuracy: 0.4642 - val_loss: 0.9704 - val_accuracy: 0.5267
Epoch 2/20
77/77 [==============================] - 28s 360ms/step - loss: 0.9114 - accuracy: 0.5771 - val_loss: 0.8227 - val_accuracy: 0.6467
Epoch 3/20
77/77 [==============================] - 28s 360ms/step - loss: 0.7511 - accuracy: 0.6802 - val_loss: 0.6948 - val_accuracy: 0.7067
Epoch 4/20
77/77 [==============================] - 28s 364ms/step - loss: 0.5760 - accuracy: 0.7693 - val_loss: 0.5250 - val_accuracy: 0.7900
Epoch 5/20
77/77 [==============================] - 28s 362ms/step - loss: 0.3939 - accuracy: 0.8470 - val_loss: 0.3647 - val_accuracy: 0.8867
Epoch 6/20
77/77 [==============================] - 28s 363ms/step - loss: 0.3820 - accuracy: 0.8605 - val_loss: 0.5255 - val_accuracy: 0.7800
Epoch 7/20
77/77 [==============================] - 28s 363ms/step - loss: 0.3203 - accuracy: 0.8806 - val_loss: 0.2863 - val_accuracy: 0.8800

In [ ]:
score = model4.evaluate(test_gen, verbose=0)

In [ ]:
print("Accuracy of evaluation data is ",score[1])

Accuracy of evaluation data is  0.9407407641410828


In [ ]:
preds = model4.predict(train_gen)


77/77 [==============================] - 10s 129ms/step
[[270 267 278]
 [285 264 266]
 [265 277 273]]


In [ ]:
prediction = np.argmax(preds, axis = 1)
print(confusion_matrix(train_gen.labels, prediction))

In [ ]:
preds[6]

array([6.699941e-04, 5.354987e-06, 1.000000e+00], dtype=float32)

In [ ]:
import numpy as np

In [ ]:
print(preds[100])

[4.1015996e-11 3.6575400e-08 1.0000000e+00]
